(add-include-book-dir :acl2s-modes "/root/acl2/books/acl2s")
(ld "acl2s-mode.lsp" :dir :acl2s-modes)
(acl2s-defaults :set verbosity-level 1)
(set-inhibit-warnings! "Invariant-risk" "theory")
(reset-prehistory t)
(in-package "ACL2S")
:q
(defun print-ttag-note (val active-book-name include-bookp deferred-p state)
 (declare (xargs :stobjs state)
          (ignore val active-book-name include-bookp deferred-p))
 state)
(defun print-deferred-ttag-notes-summary (state)
 state)
(save-exec "acl2s" "ACL2s Mode")
